-- MySQL Script generated by MySQL Workbench
-- ven. 13 août 2021 15:42:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema expressfood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema expressfood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `expressfood` ;
USE `expressfood` ;

-- -----------------------------------------------------
-- Table `expressfood`.`type_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`type_produit` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`fiche_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`fiche_produit` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type_produit_id` TINYINT UNSIGNED NOT NULL,
  `nom` VARCHAR(32) NOT NULL,
  `img_file_path` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `recette` TEXT NULL DEFAULT NULL,
  `prix` DECIMAL(4,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produit_type_produit1_idx` (`type_produit_id` ASC),
  CONSTRAINT `fk_produit_type_produit1`
    FOREIGN KEY (`type_produit_id`)
    REFERENCES `expressfood`.`type_produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`ligne_menu_du_jour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`ligne_menu_du_jour` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fiche_produit_id` SMALLINT UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`, `fiche_produit_id`),
  INDEX `fk_ligne_menu_du_jour_fiche_produit1_idx` (`fiche_produit_id` ASC),
  CONSTRAINT `fk_ligne_menu_du_jour_fiche_produit1`
    FOREIGN KEY (`fiche_produit_id`)
    REFERENCES `expressfood`.`fiche_produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`utilisateur` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(32) NOT NULL,
  `prenom` VARCHAR(32) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`statut_livreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`statut_livreur` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `statut` VARCHAR(12) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`livreur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`livreur` (
  `utilisateur_id` INT UNSIGNED NOT NULL,
  `statut_livreur_id` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `telephone` VARCHAR(15) NOT NULL,
  INDEX `fk_livreur_utilisateur1_idx` (`utilisateur_id` ASC),
  INDEX `fk_livreur_statut_livreur1_idx` (`statut_livreur_id` ASC),
  PRIMARY KEY (`utilisateur_id`),
  CONSTRAINT `fk_livreur_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `expressfood`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livreur_statut_livreur1`
    FOREIGN KEY (`statut_livreur_id`)
    REFERENCES `expressfood`.`statut_livreur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`statut_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`statut_commande` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `statut` VARCHAR(45) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`client` (
  `utilisateur_id` INT UNSIGNED NOT NULL,
  `telephone` VARCHAR(15) NULL,
  PRIMARY KEY (`utilisateur_id`),
  INDEX `fk_client_utilisateur1_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_client_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `expressfood`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`adresse_client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`adresse_client` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_utilisateur_id` INT UNSIGNED NOT NULL,
  `numero` SMALLINT UNSIGNED NULL,
  `type_de_voie` VARCHAR(32) NULL,
  `nom_de_voie` VARCHAR(255) NULL,
  `complement` VARCHAR(255) NULL,
  `code_postal` SMALLINT UNSIGNED NOT NULL,
  `ville` VARCHAR(255) NOT NULL,
  `longitude` DECIMAL(9,6) NULL,
  `latitude` DECIMAL(9,6) NULL,
  `principale` TINYINT(1) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `client_utilisateur_id`),
  INDEX `fk_adresse_client_client1_idx` (`client_utilisateur_id` ASC),
  CONSTRAINT `fk_adresse_client_client1`
    FOREIGN KEY (`client_utilisateur_id`)
    REFERENCES `expressfood`.`client` (`utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`reglement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`reglement` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_utilisateur_id` INT UNSIGNED NOT NULL,
  `montant` DECIMAL(5,2) UNSIGNED NOT NULL,
  `date_paiement` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `client_utilisateur_id`),
  INDEX `fk_reglement_client1_idx` (`client_utilisateur_id` ASC),
  CONSTRAINT `fk_reglement_client1`
    FOREIGN KEY (`client_utilisateur_id`)
    REFERENCES `expressfood`.`client` (`utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`commande` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reglement_client_utilisateur_id` INT UNSIGNED NOT NULL,
  `reglement_id` INT UNSIGNED NOT NULL,
  `adresse_client_id` INT UNSIGNED NOT NULL,
  `heure_prise_en_charge` DATETIME NULL DEFAULT NULL,
  `heure_remise_client` DATETIME NULL DEFAULT NULL,
  `livreur_utilisateur_id` INT UNSIGNED NULL DEFAULT NULL,
  `statut_commande_id` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`, `reglement_client_utilisateur_id`, `reglement_id`, `adresse_client_id`),
  INDEX `fk_commande_livreur1_idx` (`livreur_utilisateur_id` ASC),
  INDEX `fk_commande_statut_commande1_idx` (`statut_commande_id` ASC),
  INDEX `fk_commande_adresse_client1_idx` (`adresse_client_id` ASC),
  INDEX `fk_commande_reglement1_idx` (`reglement_id` ASC, `reglement_client_utilisateur_id` ASC),
  CONSTRAINT `fk_commande_livreur1`
    FOREIGN KEY (`livreur_utilisateur_id`)
    REFERENCES `expressfood`.`livreur` (`utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_statut_commande1`
    FOREIGN KEY (`statut_commande_id`)
    REFERENCES `expressfood`.`statut_commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_adresse_client1`
    FOREIGN KEY (`adresse_client_id`)
    REFERENCES `expressfood`.`adresse_client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_reglement1`
    FOREIGN KEY (`reglement_id` , `reglement_client_utilisateur_id`)
    REFERENCES `expressfood`.`reglement` (`id` , `client_utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`ligne_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`ligne_commande` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `commande_id` INT UNSIGNED NOT NULL,
  `quantite` SMALLINT NOT NULL,
  `fiche_produit_id` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `commande_id`),
  INDEX `fk_ligne_commande_commande1_idx` (`commande_id` ASC),
  INDEX `fk_ligne_commande_fiche_produit1_idx` (`fiche_produit_id` ASC),
  CONSTRAINT `fk_ligne_commande_commande1`
    FOREIGN KEY (`commande_id`)
    REFERENCES `expressfood`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ligne_commande_fiche_produit1`
    FOREIGN KEY (`fiche_produit_id`)
    REFERENCES `expressfood`.`fiche_produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`admin` (
  `utilisateur_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`utilisateur_id`),
  CONSTRAINT `fk_admin_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `expressfood`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`cuisinier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`cuisinier` (
  `utilisateur_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`utilisateur_id`),
  CONSTRAINT `fk_cuisinier_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `expressfood`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`produit` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ligne_menu_du_jour_id` SMALLINT UNSIGNED NOT NULL,
  `ligne_menu_du_jour_fiche_produit_id` SMALLINT UNSIGNED NOT NULL,
  `livreur_utilisateur_id` INT UNSIGNED NULL DEFAULT NULL,
  `cuisinier_utilisateur_id` INT UNSIGNED NOT NULL,
  `commande_id` INT UNSIGNED NULL,
  `commande_reglement_client_utilisateur_id` INT UNSIGNED NULL,
  `commande_reglement_id` INT UNSIGNED NULL,
  `commande_adresse_client_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`, `ligne_menu_du_jour_id`, `ligne_menu_du_jour_fiche_produit_id`, `cuisinier_utilisateur_id`),
  INDEX `fk_produit_ligne_menu_du_jour1_idx` (`ligne_menu_du_jour_id` ASC, `ligne_menu_du_jour_fiche_produit_id` ASC),
  INDEX `fk_produit_livreur1_idx` (`livreur_utilisateur_id` ASC),
  INDEX `fk_produit_cuisinier1_idx` (`cuisinier_utilisateur_id` ASC),
  INDEX `fk_produit_commande1_idx` (`commande_id` ASC, `commande_reglement_client_utilisateur_id` ASC, `commande_reglement_id` ASC, `commande_adresse_client_id` ASC),
  CONSTRAINT `fk_produit_ligne_menu_du_jour1`
    FOREIGN KEY (`ligne_menu_du_jour_id` , `ligne_menu_du_jour_fiche_produit_id`)
    REFERENCES `expressfood`.`ligne_menu_du_jour` (`id` , `fiche_produit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_livreur1`
    FOREIGN KEY (`livreur_utilisateur_id`)
    REFERENCES `expressfood`.`livreur` (`utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_cuisinier1`
    FOREIGN KEY (`cuisinier_utilisateur_id`)
    REFERENCES `expressfood`.`cuisinier` (`utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produit_commande1`
    FOREIGN KEY (`commande_id` , `commande_reglement_client_utilisateur_id` , `commande_reglement_id` , `commande_adresse_client_id`)
    REFERENCES `expressfood`.`commande` (`id` , `reglement_client_utilisateur_id` , `reglement_id` , `adresse_client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expressfood`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expressfood`.`position` (
  `livreur_utilisateur_id` INT UNSIGNED NOT NULL,
  `longitude` DECIMAL(9,6) NULL,
  `latitude` DECIMAL(9,6) NULL,
  PRIMARY KEY (`livreur_utilisateur_id`),
  CONSTRAINT `fk_position_livreur1`
    FOREIGN KEY (`livreur_utilisateur_id`)
    REFERENCES `expressfood`.`livreur` (`utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
